#!/bin/sh

# The command is called the following way:
#   $events_command MSG IN jabber@id [file] (when receiving a message)
#   $events_command MSG OUT jabber@id       (when sending a message)
#   $events_command MSG MUC room_id [file]  (when receiving a MUC message)
#   $events_command STATUS X jabber@id      (new buddy status is X)
#   $events_command UNREAD N                (number of unread buddy buffers)

if [ "$1" = "MSG" ]; then
	if [ \( "$2" = "IN" \) -o \( "$2" = "MUC" \) ]; then
		echo "$3" > /tmp/qtraynotify.fifo &
	fi
fi

